{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.db.username | quote }}
  password: {{ .Values.db.password | quote }}
{{- end }}
---
{{- if not .Values.keycloak.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-keycloak
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.admin.username | quote }}
  password: {{ .Values.keycloak.admin.password | quote }}
{{- end }}
---
{{- if not .Values.objectStorage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-objectstorage
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  root-user: {{ .Values.objectStorage.accessKey | quote }}
  root-password: {{ .Values.objectStorage.secretKey | quote }}
{{- end }}
