[request_definition]
r = userId, orgId, objectType, objectId, action

[policy_definition]
p = role, orgId, objectType, objectId, action

[role_definition]
g = _, _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (p.role == "PUBLIC" || g(r.userId, p.role, r.orgId)) && (p.orgId == "*" || r.orgId == p.orgId) && (p.objectType == "*" || p.objectType == r.objectType || keyMatch2(r.objectType, p.objectType)) && (p.objectId == "*" || p.objectId == r.objectId) && (p.action == "*" || p.action == r.action)
